location="eastus"
rg-name="rg-backend-demo"
cosmosdb_name="demo-cosmosdb-mongo"
fn_storage_account_name="fnstorageaccountdemo"
fn_app_service_plan_name="fn-app-service-plan-demo"
function_app_name="demo-func-app100"
apim_name="demo-backend-apim"
environment="dev"